POST http://localhost:5000/api/library
Content-Type: application/json

{
  "Title": "Anna Karenina",
  "Author": "Leo Tolstoy",
  "Content": "Happy families are all alike; every unhappy family is unhappy in its own way."
}

###
